name             'solaris_pkg'
maintainer       'itunixadminall'
maintainer_email 'itunixadminall@nordstrom.com'
license          'All rights reserved'
description      'Installs/Configures solaris_pkg'
long_description 'Sets up a server for installing Solaris packages'
version          '0.2.0'
